import { PermissionsBitField, EmbedBuilder } from "discord.js";
import { safeRespond } from "../../utils/helpers.js";
import { asEmbedPayload } from "../../utils/embeds.js";
import { generateServerRules } from "../../utils/ai.js";

export default {
    data: {
        name: "generate_rules",
        description: "Use AI to generate a custom rules embed for this server.",
        default_member_permissions: String(PermissionsBitField.Flags.ManageGuild),
        dm_permission: false,
        options: [
            {
                name: "post_to",
                description: "Channel to post the generated rules in (defaults to current channel).",
                type: 7, // CHANNEL
                required: false,
            },
        ],
    },

    async execute(interaction) {
        if (!interaction.guildId) return;

        await interaction.deferReply({ ephemeral: true });

        const guild = interaction.guild;
        const target = interaction.options.getChannel("post_to") ?? interaction.channel;

        const channelNames = [...guild.channels.cache.values()]
            .filter(c => c.isTextBased && typeof c.name === "string")
            .map(c => c.name)
            .slice(0, 30);

        const roleNames = [...guild.roles.cache.values()]
            .filter(r => r.id !== guild.id && !r.managed)
            .map(r => r.name)
            .slice(0, 20);

        const rulesText = await generateServerRules({
            name: guild.name,
            channelNames,
            roleNames,
            memberCount: guild.memberCount,
        });

        if (!rulesText || rulesText === "ERROR" || rulesText === "QUOTA_EXCEEDED") {
            return safeRespond(interaction, asEmbedPayload({
                guildId: guild.id, type: "error",
                title: "❌ AI Error",
                description: "Failed to generate rules. Please try again.",
            }));
        }

        const rulesEmbed = new EmbedBuilder()
            .setColor(0xED4245)
            .setTitle(`📜 ${guild.name} — Server Rules`)
            .setDescription(rulesText.length > 4096 ? rulesText.slice(0, 4093) + "..." : rulesText)
            .setTimestamp()
            .setFooter({ text: "Generated by Claude AI — Edit as needed." });

        await target.send({ embeds: [rulesEmbed] }).catch(() => null);

        return safeRespond(interaction, asEmbedPayload({
            guildId: guild.id, type: "success",
            title: "✅ Rules Generated",
            description: `Posted to <#${target.id}>. Edit the message if you want to customize anything.`,
        }));
    },
};
