import { GoogleGenerativeAI } from "@google/generative-ai";
import { messageBuffer } from "../../events/messageCreate.js";
import { replyEmbed } from "../../utils/embeds.js";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

export default {
    name: "summary",
    description: "Summarize the last 100 messages in the channel (Contextual RAG Catch-Up)",
    async execute(message, args) {
        const channelId = message.channel.id;
        const buffer = messageBuffer.get(channelId);

        if (!buffer || buffer.length === 0) {
            return replyEmbed(message, {
                type: "error",
                title: "❌ No Context",
                description: "There are no recent messages in this channel to summarize."
            });
        }

        // Inform user it's processing
        const loadingMessage = await replyEmbed(message, {
            type: "info",
            title: "⏳ Generating Summary...",
            description: "Reading the last " + buffer.length + " messages..."
        });

        const chatContext = buffer.map(m => `[${new Date(m.timestamp).toLocaleTimeString()}] ${m.author}: ${m.content}`).join("\n");
        const prompt = `You are an AI assistant analyzing a Discord chat.
I will provide you with a log of up to 100 recent messages from this channel.
Your task is to summarize the missed conversation for returning users.

Format your response as a bulleted list covering:
- **Topics**: What was discussed?
- **Key Decisions**: Any agreements or conclusions reached?
- **Vibes**: What is the general mood or tone of the discussion?

Keep it concise, actionable, and visually appealing.

Chat Log:
${chatContext}`;

        try {
            const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
            const result = await model.generateContent(prompt);
            const responseText = result.response.text();

            await loadingMessage.edit({
                embeds: [{
                    title: "📄 Chat Catch-Up Summary",
                    description: responseText,
                    color: 0x57F287,
                    footer: { text: "Generated by Gemini 1.5" },
                    timestamp: new Date().toISOString()
                }]
            });
        } catch (error) {
            console.error("Gemini AI Summarization Error:", error);
            await loadingMessage.edit({
                embeds: [{
                    title: "❌ Summary Failed",
                    description: "An error occurred while contacting the summarization model.",
                    color: 0xED4245
                }]
            });
        }
    }
};
